repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: nginx-hf
    namespace: nginx-hf
    chart: bitnami/nginx
    values:
      - image:
          debug: false
      - service:
          type: ClusterIP
      - extraEnvVars:
          - name: TEST_VARIABLE_1
            value: {{ .Environment.Values.TEST_VARIABLE_1 }}
