---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-local-k8s
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    env: dev
    owner: oisis
type: Opaque
stringData:
  name: local
  server: https://kubernetes.default.svc
  config: |
    {"tlsClientConfig":{"insecure": false}}
