---
apiVersion: v1
kind: Secret
metadata:
  name: repo-gitlab-oisis-argocd
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/oisis/ArgoCD-example.git
