appconfig:
  - name: "ingress-nginx"
    namespace: "ingress-nginx"
    project: "default"
    repoUrl: "https://kubernetes.github.io/ingress-nginx"
    chart: ingress-nginx
    targetRevision: "4.12.0-beta.0"
