appconfig:
  - name: "argocd"
    namespace: "argocd"
    project: "default"
    repoUrl: "https://argoproj.github.io/argo-helm"
    chart: "argo-cd"
    targetRevision: "8.5.6"
    automatedPrune: "false"