appconfig:
  - name: "argocd"
    namespace: "argocd"
    project: "default"
    repoUrl: "https://argoproj.github.io/argo-helm"
    chart: "argo-cd"
    targetRevision: "7.8.15"
    syncPolicyValidate: "true"
